export const SETLOGININFO = 'setLoginInfo'
export const SETUSERINFO = 'setUserInfo'
export const SETPERMS = 'setPerms'
export const CHANGEMENUDATA = 'changeMenuData'
export const CHANGEAPP = 'changeApp'
