export const SETLOGININFO = 'setLoginInfo'
export const SETUSERINFO = 'setUserInfo'
export const SETPERMS = 'setPerms'
export const GETADDRESS = 'getAddress'
export const GETROUTERS = 'getRouters'
export const CHANGEMENUDATA = 'changeMenuData'
